### ISSUE TITLE
Error on npm run deploy

### ISSUE THREAD

**Issue by Technologx** [kaaaxcreators/Discord-MusicBot#179]
**Describe the bug**
  ```
TypeError: Cannot read properties of undefined (reading 'map')
    at EnvError (/Users/BelleMorte/Desktop/djblaze/dist/index.js:136:14)
    at Object.<anonymous> (/Users/BelleMorte/Desktop/djblaze/dist/index.js:20:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

```
**To Reproduce**
I just followed the guide on adding my tokens and ran npm run deploy and ran into the error.

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/1CLHbld55T4eTj97o4ck2ac7M0DznunjC/view?usp=sharing
**Details (please complete the following information):**

- Bot Version: latest
- Hosting Provider private host, right now on my laptop

**Additional context**

**Comment by Technologx** [comment]
You can close this I can't afford to use CapRover

**Comment by kaaax0815** [comment]
Please provide more details and then reopen this issue. ENV File Contents (not the token!)
